{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Hyperopt.ipynb","provenance":[],"collapsed_sections":[],"authorship_tag":"ABX9TyNvDMurPZqZ+BuKW7i3Sgdl"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU","widgets":{"application/vnd.jupyter.widget-state+json":{"2c218057107d41698a168d956a9abdf6":{"model_module":"@jupyter-widgets/controls","model_name":"HBoxModel","state":{"_view_name":"HBoxView","_dom_classes":[],"_model_name":"HBoxModel","_view_module":"@jupyter-widgets/controls","_model_module_version":"1.5.0","_view_count":null,"_view_module_version":"1.5.0","box_style":"","layout":"IPY_MODEL_9c97b6aa0b394200ab1abb40bd6d12b2","_model_module":"@jupyter-widgets/controls","children":["IPY_MODEL_6e86a67843b14ce684e1fd522909009e","IPY_MODEL_21167fab426d4a71a93ac2c3bad04d27"]}},"9c97b6aa0b394200ab1abb40bd6d12b2":{"model_module":"@jupyter-widgets/base","model_name":"LayoutModel","state":{"_view_name":"LayoutView","grid_template_rows":null,"right":null,"justify_content":null,"_view_module":"@jupyter-widgets/base","overflow":null,"_model_module_version":"1.2.0","_view_count":null,"flex_flow":null,"width":null,"min_width":null,"border":null,"align_items":null,"bottom":null,"_model_module":"@jupyter-widgets/base","top":null,"grid_column":null,"overflow_y":null,"overflow_x":null,"grid_auto_flow":null,"grid_area":null,"grid_template_columns":null,"flex":null,"_model_name":"LayoutModel","justify_items":null,"grid_row":null,"max_height":null,"align_content":null,"visibility":null,"align_self":null,"height":null,"min_height":null,"padding":null,"grid_auto_rows":null,"grid_gap":null,"max_width":null,"order":null,"_view_module_version":"1.2.0","grid_template_areas":null,"object_position":null,"object_fit":null,"grid_auto_columns":null,"margin":null,"display":null,"left":null}},"6e86a67843b14ce684e1fd522909009e":{"model_module":"@jupyter-widgets/controls","model_name":"FloatProgressModel","state":{"_view_name":"ProgressView","style":"IPY_MODEL_e589c074f203450db3c7c1211cad5584","_dom_classes":[],"description":"","_model_name":"FloatProgressModel","bar_style":"info","max":1,"_view_module":"@jupyter-widgets/controls","_model_module_version":"1.5.0","value":1,"_view_count":null,"_view_module_version":"1.5.0","orientation":"horizontal","min":0,"description_tooltip":null,"_model_module":"@jupyter-widgets/controls","layout":"IPY_MODEL_569ee684990547309e666dd42808337f"}},"21167fab426d4a71a93ac2c3bad04d27":{"model_module":"@jupyter-widgets/controls","model_name":"HTMLModel","state":{"_view_name":"HTMLView","style":"IPY_MODEL_a99d36384a224757a8b7297c4423ccef","_dom_classes":[],"description":"","_model_name":"HTMLModel","placeholder":"​","_view_module":"@jupyter-widgets/controls","_model_module_version":"1.5.0","value":" 170500096/? [00:20&lt;00:00, 34337318.02it/s]","_view_count":null,"_view_module_version":"1.5.0","description_tooltip":null,"_model_module":"@jupyter-widgets/controls","layout":"IPY_MODEL_0c10225f3e8a46caa5d963d9bbf9348d"}},"e589c074f203450db3c7c1211cad5584":{"model_module":"@jupyter-widgets/controls","model_name":"ProgressStyleModel","state":{"_view_name":"StyleView","_model_name":"ProgressStyleModel","description_width":"initial","_view_module":"@jupyter-widgets/base","_model_module_version":"1.5.0","_view_count":null,"_view_module_version":"1.2.0","bar_color":null,"_model_module":"@jupyter-widgets/controls"}},"569ee684990547309e666dd42808337f":{"model_module":"@jupyter-widgets/base","model_name":"LayoutModel","state":{"_view_name":"LayoutView","grid_template_rows":null,"right":null,"justify_content":null,"_view_module":"@jupyter-widgets/base","overflow":null,"_model_module_version":"1.2.0","_view_count":null,"flex_flow":null,"width":null,"min_width":null,"border":null,"align_items":null,"bottom":null,"_model_module":"@jupyter-widgets/base","top":null,"grid_column":null,"overflow_y":null,"overflow_x":null,"grid_auto_flow":null,"grid_area":null,"grid_template_columns":null,"flex":null,"_model_name":"LayoutModel","justify_items":null,"grid_row":null,"max_height":null,"align_content":null,"visibility":null,"align_self":null,"height":null,"min_height":null,"padding":null,"grid_auto_rows":null,"grid_gap":null,"max_width":null,"order":null,"_view_module_version":"1.2.0","grid_template_areas":null,"object_position":null,"object_fit":null,"grid_auto_columns":null,"margin":null,"display":null,"left":null}},"a99d36384a224757a8b7297c4423ccef":{"model_module":"@jupyter-widgets/controls","model_name":"DescriptionStyleModel","state":{"_view_name":"StyleView","_model_name":"DescriptionStyleModel","description_width":"","_view_module":"@jupyter-widgets/base","_model_module_version":"1.5.0","_view_count":null,"_view_module_version":"1.2.0","_model_module":"@jupyter-widgets/controls"}},"0c10225f3e8a46caa5d963d9bbf9348d":{"model_module":"@jupyter-widgets/base","model_name":"LayoutModel","state":{"_view_name":"LayoutView","grid_template_rows":null,"right":null,"justify_content":null,"_view_module":"@jupyter-widgets/base","overflow":null,"_model_module_version":"1.2.0","_view_count":null,"flex_flow":null,"width":null,"min_width":null,"border":null,"align_items":null,"bottom":null,"_model_module":"@jupyter-widgets/base","top":null,"grid_column":null,"overflow_y":null,"overflow_x":null,"grid_auto_flow":null,"grid_area":null,"grid_template_columns":null,"flex":null,"_model_name":"LayoutModel","justify_items":null,"grid_row":null,"max_height":null,"align_content":null,"visibility":null,"align_self":null,"height":null,"min_height":null,"padding":null,"grid_auto_rows":null,"grid_gap":null,"max_width":null,"order":null,"_view_module_version":"1.2.0","grid_template_areas":null,"object_position":null,"object_fit":null,"grid_auto_columns":null,"margin":null,"display":null,"left":null}}}}},"cells":[{"cell_type":"code","metadata":{"id":"U-6KC_blOM4r","executionInfo":{"status":"ok","timestamp":1602328537549,"user_tz":-120,"elapsed":20421,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}},"outputId":"4d3253c1-b743-4601-f4e6-2d74a765b7cb","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["!pip install -U ray"],"execution_count":12,"outputs":[{"output_type":"stream","text":["Collecting ray\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ea/ed/ff896981d4ac684614236f73c1a20cde5f6cb0e2a590c182f62b22706ab4/ray-1.0.0-cp36-cp36m-manylinux1_x86_64.whl (22.9MB)\n","\u001b[K     |████████████████████████████████| 22.9MB 133kB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: jsonschema in /usr/local/lib/python3.6/dist-packages (from ray) (2.6.0)\n","Collecting colorful\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/b0/8e/e386e248266952d24d73ed734c2f5513f34d9557032618c8910e605dfaf6/colorful-0.5.4-py2.py3-none-any.whl (201kB)\n","\u001b[K     |████████████████████████████████| 204kB 42.7MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: click>=7.0 in /usr/local/lib/python3.6/dist-packages (from ray) (7.1.2)\n","Requirement already satisfied, skipping upgrade: google in /usr/local/lib/python3.6/dist-packages (from ray) (2.0.3)\n","Requirement already satisfied, skipping upgrade: requests in /usr/local/lib/python3.6/dist-packages (from ray) (2.23.0)\n","Requirement already satisfied, skipping upgrade: prometheus-client>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from ray) (0.8.0)\n","Collecting aiohttp\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/7c/39/7eb5f98d24904e0f6d3edb505d4aa60e3ef83c0a58d6fe18244a51757247/aiohttp-3.6.2-cp36-cp36m-manylinux1_x86_64.whl (1.2MB)\n","\u001b[K     |████████████████████████████████| 1.2MB 44.5MB/s \n","\u001b[?25hCollecting aiohttp-cors\n","  Downloading https://files.pythonhosted.org/packages/13/e7/e436a0c0eb5127d8b491a9b83ecd2391c6ff7dcd5548dfaec2080a2340fd/aiohttp_cors-0.7.0-py3-none-any.whl\n","Collecting gpustat\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/b4/69/d8c849715171aeabd61af7da080fdc60948b5a396d2422f1f4672e43d008/gpustat-0.6.0.tar.gz (78kB)\n","\u001b[K     |████████████████████████████████| 81kB 9.2MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: protobuf>=3.8.0 in /usr/local/lib/python3.6/dist-packages (from ray) (3.12.4)\n","Collecting opencensus\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/8a/9c/d40e3408e72d02612acf247d829e3fa9ff15c59f7ad81418ed79962f8681/opencensus-0.7.10-py2.py3-none-any.whl (126kB)\n","\u001b[K     |████████████████████████████████| 133kB 44.7MB/s \n","\u001b[?25hCollecting py-spy>=0.2.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/8e/a7/ab45c9ee3c4654edda3efbd6b8e2fa4962226718a7e3e3be6e3926bf3617/py_spy-0.3.3-py2.py3-none-manylinux1_x86_64.whl (2.9MB)\n","\u001b[K     |████████████████████████████████| 2.9MB 40.4MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: filelock in /usr/local/lib/python3.6/dist-packages (from ray) (3.0.12)\n","Collecting aioredis\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/b0/64/1b1612d0a104f21f80eb4c6e1b6075f2e6aba8e228f46f229cfd3fdac859/aioredis-1.3.1-py3-none-any.whl (65kB)\n","\u001b[K     |████████████████████████████████| 71kB 7.8MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from ray) (1.0.0)\n","Requirement already satisfied, skipping upgrade: numpy>=1.16 in /usr/local/lib/python3.6/dist-packages (from ray) (1.18.5)\n","Collecting colorama\n","  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl\n","Collecting redis<3.5.0,>=3.3.2\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/f0/05/1fc7feedc19c123e7a95cfc9e7892eb6cdd2e5df4e9e8af6384349c1cc3d/redis-3.4.1-py2.py3-none-any.whl (71kB)\n","\u001b[K     |████████████████████████████████| 71kB 8.5MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: grpcio>=1.28.1 in /usr/local/lib/python3.6/dist-packages (from ray) (1.32.0)\n","Requirement already satisfied, skipping upgrade: pyyaml in /usr/local/lib/python3.6/dist-packages (from ray) (3.13)\n","Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/local/lib/python3.6/dist-packages (from google->ray) (4.6.3)\n","Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->ray) (1.24.3)\n","Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->ray) (2.10)\n","Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->ray) (3.0.4)\n","Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->ray) (2020.6.20)\n","Collecting multidict<5.0,>=4.5\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/1a/95/f50352b5366e7d579e8b99631680a9e32e1b22adfa1629a8f23b1d22d5e2/multidict-4.7.6-cp36-cp36m-manylinux1_x86_64.whl (148kB)\n","\u001b[K     |████████████████████████████████| 153kB 45.9MB/s \n","\u001b[?25hCollecting yarl<2.0,>=1.0\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/01/c9/379b807a9c298b9694d0af8ee4260be7d40ab1a11fb9d4ae9e70b1e69d96/yarl-1.6.0-cp36-cp36m-manylinux1_x86_64.whl (257kB)\n","\u001b[K     |████████████████████████████████| 266kB 41.4MB/s \n","\u001b[?25hCollecting idna-ssl>=1.0; python_version < \"3.7\"\n","  Downloading https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz\n","Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.5; python_version < \"3.7\" in /usr/local/lib/python3.6/dist-packages (from aiohttp->ray) (3.7.4.3)\n","Collecting async-timeout<4.0,>=3.0\n","  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl\n","Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/local/lib/python3.6/dist-packages (from aiohttp->ray) (20.2.0)\n","Requirement already satisfied, skipping upgrade: six>=1.7 in /usr/local/lib/python3.6/dist-packages (from gpustat->ray) (1.15.0)\n","Requirement already satisfied, skipping upgrade: nvidia-ml-py3>=7.352.0 in /usr/local/lib/python3.6/dist-packages (from gpustat->ray) (7.352.0)\n","Requirement already satisfied, skipping upgrade: psutil in /usr/local/lib/python3.6/dist-packages (from gpustat->ray) (5.4.8)\n","Collecting blessings>=1.6\n","  Downloading https://files.pythonhosted.org/packages/03/74/489f85a78247609c6b4f13733cbf3ba0d864b11aa565617b645d6fdf2a4a/blessings-1.7-py3-none-any.whl\n","Requirement already satisfied, skipping upgrade: setuptools in /usr/local/lib/python3.6/dist-packages (from protobuf>=3.8.0->ray) (50.3.0)\n","Collecting opencensus-context==0.1.1\n","  Downloading https://files.pythonhosted.org/packages/2b/b7/720d4507e97aa3916ac47054cd75490de6b6148c46d8c2c487638f16ad95/opencensus_context-0.1.1-py2.py3-none-any.whl\n","Requirement already satisfied, skipping upgrade: google-api-core<2.0.0,>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from opencensus->ray) (1.16.0)\n","Collecting hiredis\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/ed/7d/6acf1c8d4f2fb327ff6feec000b4c56a20628fbe966a4c7cd16c0b80343c/hiredis-1.1.0-cp36-cp36m-manylinux2010_x86_64.whl (61kB)\n","\u001b[K     |████████████████████████████████| 61kB 7.9MB/s \n","\u001b[?25hCollecting contextvars; python_version >= \"3.6\" and python_version < \"3.7\"\n","  Downloading https://files.pythonhosted.org/packages/83/96/55b82d9f13763be9d672622e1b8106c85acb83edd7cc2fa5bc67cd9877e9/contextvars-2.4.tar.gz\n","Requirement already satisfied, skipping upgrade: google-auth<2.0dev,>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (1.17.2)\n","Requirement already satisfied, skipping upgrade: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (1.52.0)\n","Requirement already satisfied, skipping upgrade: pytz in /usr/local/lib/python3.6/dist-packages (from google-api-core<2.0.0,>=1.0.0->opencensus->ray) (2018.9)\n","Collecting immutables>=0.9\n","\u001b[?25l  Downloading https://files.pythonhosted.org/packages/99/e0/ea6fd4697120327d26773b5a84853f897a68e33d3f9376b00a8ff96e4f63/immutables-0.14-cp36-cp36m-manylinux1_x86_64.whl (98kB)\n","\u001b[K     |████████████████████████████████| 102kB 11.5MB/s \n","\u001b[?25hRequirement already satisfied, skipping upgrade: rsa<5,>=3.1.4; python_version >= \"3\" in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (4.6)\n","Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (0.2.8)\n","Requirement already satisfied, skipping upgrade: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/dist-packages (from google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (4.1.1)\n","Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /usr/local/lib/python3.6/dist-packages (from rsa<5,>=3.1.4; python_version >= \"3\"->google-auth<2.0dev,>=0.4.0->google-api-core<2.0.0,>=1.0.0->opencensus->ray) (0.4.8)\n","Building wheels for collected packages: gpustat, idna-ssl, contextvars\n","  Building wheel for gpustat (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for gpustat: filename=gpustat-0.6.0-cp36-none-any.whl size=12622 sha256=ee708f1a5fc8c0b9b9594032dc9565a75b1384bf451677d5213868f579fe4a31\n","  Stored in directory: /root/.cache/pip/wheels/48/b4/d5/fb5b7f1d040f2ff20687e3bad6867d63155dbde5a7c10f4293\n","  Building wheel for idna-ssl (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for idna-ssl: filename=idna_ssl-1.1.0-cp36-none-any.whl size=3161 sha256=c5aa6c558b2a16d2e14268fcc120ba05dcd5c01c4779ed6d8aac9f79c0fe5157\n","  Stored in directory: /root/.cache/pip/wheels/d3/00/b3/32d613e19e08a739751dd6bf998cfed277728f8b2127ad4eb7\n","  Building wheel for contextvars (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for contextvars: filename=contextvars-2.4-cp36-none-any.whl size=7666 sha256=d7517b9c987efc62a5ee964904b6c10a5832d2537cd686c2454320bcedd7edf6\n","  Stored in directory: /root/.cache/pip/wheels/a5/7d/68/1ebae2668bda2228686e3c1cf16f2c2384cea6e9334ad5f6de\n","Successfully built gpustat idna-ssl contextvars\n","Installing collected packages: colorful, multidict, yarl, idna-ssl, async-timeout, aiohttp, aiohttp-cors, blessings, gpustat, immutables, contextvars, opencensus-context, opencensus, py-spy, hiredis, aioredis, colorama, redis, ray\n","Successfully installed aiohttp-3.6.2 aiohttp-cors-0.7.0 aioredis-1.3.1 async-timeout-3.0.1 blessings-1.7 colorama-0.4.3 colorful-0.5.4 contextvars-2.4 gpustat-0.6.0 hiredis-1.1.0 idna-ssl-1.1.0 immutables-0.14 multidict-4.7.6 opencensus-0.7.10 opencensus-context-0.1.1 py-spy-0.3.3 ray-1.0.0 redis-3.4.1 yarl-1.6.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"XX4QQKgiFuhw","executionInfo":{"status":"ok","timestamp":1602326450936,"user_tz":-120,"elapsed":4909,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}},"outputId":"26c825d3-599b-4c84-dd07-bdbcfec714b4","colab":{"base_uri":"https://localhost:8080/","height":34}},"source":["import os\n","import time\n","import copy\n","\n","from collections import OrderedDict\n","\n","import torch\n","import torch.nn as nn\n","import torch.optim as optim\n","import torch.nn.functional as F\n","\n","import torchvision\n","from torchvision import datasets\n","from torchvision import transforms\n","from torch.utils.data.sampler import SubsetRandomSampler\n","\n","from torch.utils.tensorboard import SummaryWriter\n","\n","import matplotlib.pyplot as plt\n","import numpy as np\n","\n","print(torch.cuda.is_available())"],"execution_count":1,"outputs":[{"output_type":"stream","text":["True\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"Eu5V-_dzOUeh","executionInfo":{"status":"ok","timestamp":1602330308780,"user_tz":-120,"elapsed":900,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["from functools import partial\n","import ray\n","from ray import tune\n","from ray.tune import CLIReporter\n","from ray.tune.schedulers import ASHAScheduler"],"execution_count":19,"outputs":[]},{"cell_type":"code","metadata":{"id":"Hm3scSZrGSR6","executionInfo":{"status":"ok","timestamp":1602326509381,"user_tz":-120,"elapsed":1239,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["\"\"\"\n","Create train, valid, test iterators for CIFAR-10 [1].\n","Easily extended to MNIST, CIFAR-100 and Imagenet.\n","[1]: https://discuss.pytorch.org/t/feedback-on-pytorch-for-kaggle-competitions/2252/4\n","\"\"\"\n","\n","def plot_images(images, cls_true, cls_pred=None):\n","    \"\"\"\n","    Adapted from https://github.com/Hvass-Labs/TensorFlow-Tutorials/\n","    \"\"\"\n","    fig, axes = plt.subplots(3, 3)\n","\n","    for i, ax in enumerate(axes.flat):\n","        # plot img\n","        ax.imshow(images[i, :, :, :], interpolation='spline16')\n","\n","        # show true & predicted classes\n","        cls_true_name = label_names[cls_true[i]]\n","        if cls_pred is None:\n","            xlabel = \"{0} ({1})\".format(cls_true_name, cls_true[i])\n","        else:\n","            cls_pred_name = label_names[cls_pred[i]]\n","            xlabel = \"True: {0}\\nPred: {1}\".format(\n","                cls_true_name, cls_pred_name\n","            )\n","        ax.set_xlabel(xlabel)\n","        ax.set_xticks([])\n","        ax.set_yticks([])\n","\n","    plt.show()\n","\n","def get_train_valid_loader(data_dir,\n","                           batch_size,\n","                           augment,\n","                           random_seed,\n","                           valid_size=0.1,\n","                           shuffle=True,\n","                           show_sample=False,\n","                           num_workers=4,\n","                           pin_memory=False):\n","    \"\"\"\n","    Utility function for loading and returning train and valid\n","    multi-process iterators over the CIFAR-10 dataset. A sample\n","    9x9 grid of the images can be optionally displayed.\n","    If using CUDA, num_workers should be set to 1 and pin_memory to True.\n","    Params\n","    ------\n","    - data_dir: path directory to the dataset.\n","    - batch_size: how many samples per batch to load.\n","    - augment: whether to apply the data augmentation scheme\n","      mentioned in the paper. Only applied on the train split.\n","    - random_seed: fix seed for reproducibility.\n","    - valid_size: percentage split of the training set used for\n","      the validation set. Should be a float in the range [0, 1].\n","    - shuffle: whether to shuffle the train/validation indices.\n","    - show_sample: plot 9x9 sample grid of the dataset.\n","    - num_workers: number of subprocesses to use when loading the dataset.\n","    - pin_memory: whether to copy tensors into CUDA pinned memory. Set it to\n","      True if using GPU.\n","    Returns\n","    -------\n","    - train_loader: training set iterator.\n","    - valid_loader: validation set iterator.\n","    \"\"\"\n","    error_msg = \"[!] valid_size should be in the range [0, 1].\"\n","    assert ((valid_size >= 0) and (valid_size <= 1)), error_msg\n","\n","    normalize = transforms.Normalize(\n","        mean=[0.4914, 0.4822, 0.4465],\n","        std=[0.2023, 0.1994, 0.2010],\n","    )\n","\n","    # define transforms\n","    valid_transform = transforms.Compose([\n","            transforms.ToTensor(),\n","            normalize,\n","    ])\n","    if augment:\n","        train_transform = transforms.Compose([\n","            transforms.RandomCrop(32, padding=4),\n","            transforms.RandomHorizontalFlip(),\n","            transforms.ToTensor(),\n","            normalize,\n","        ])\n","    else:\n","        train_transform = transforms.Compose([\n","            transforms.ToTensor(),\n","            normalize,\n","        ])\n","\n","    # load the dataset\n","    train_dataset = datasets.CIFAR10(\n","        root=data_dir, train=True,\n","        download=True, transform=train_transform,\n","    )\n","\n","    valid_dataset = datasets.CIFAR10(\n","        root=data_dir, train=True,\n","        download=True, transform=valid_transform,\n","    )\n","\n","    num_train = len(train_dataset)\n","    indices = list(range(num_train))\n","    split = int(np.floor(valid_size * num_train))\n","\n","    if shuffle:\n","        np.random.seed(random_seed)\n","        np.random.shuffle(indices)\n","\n","    train_idx, valid_idx = indices[split:], indices[:split]\n","    train_sampler = SubsetRandomSampler(train_idx)\n","    valid_sampler = SubsetRandomSampler(valid_idx)\n","\n","    train_loader = torch.utils.data.DataLoader(\n","        train_dataset, batch_size=batch_size, sampler=train_sampler,\n","        num_workers=num_workers, pin_memory=pin_memory,\n","    )\n","    valid_loader = torch.utils.data.DataLoader(\n","        valid_dataset, batch_size=batch_size, sampler=valid_sampler,\n","        num_workers=num_workers, pin_memory=pin_memory,\n","    )\n","\n","    # visualize some images\n","    if show_sample:\n","        sample_loader = torch.utils.data.DataLoader(\n","            train_dataset, batch_size=9, shuffle=shuffle,\n","            num_workers=num_workers, pin_memory=pin_memory,\n","        )\n","        data_iter = iter(sample_loader)\n","        images, labels = data_iter.next()\n","        X = images.numpy().transpose([0, 2, 3, 1])\n","        plot_images(X, labels)\n","\n","    loaders = {\"Train\":train_loader, \"Valid\":valid_loader} \n","    dataset_sizes = {\"Train\": len(train_dataset), \"Valid\": len(train_dataset) * valid_size}\n","    return loaders, dataset_sizes\n","\n","\n","def get_test_loader(data_dir,\n","                    batch_size,\n","                    shuffle=True,\n","                    num_workers=4,\n","                    pin_memory=False):\n","    \"\"\"\n","    Utility function for loading and returning a multi-process\n","    test iterator over the CIFAR-10 dataset.\n","    If using CUDA, num_workers should be set to 1 and pin_memory to True.\n","    Params\n","    ------\n","    - data_dir: path directory to the dataset.\n","    - batch_size: how many samples per batch to load.\n","    - shuffle: whether to shuffle the dataset after every epoch.\n","    - num_workers: number of subprocesses to use when loading the dataset.\n","    - pin_memory: whether to copy tensors into CUDA pinned memory. Set it to\n","      True if using GPU.\n","    Returns\n","    -------\n","    - data_loader: test set iterator.\n","    \"\"\"\n","    normalize = transforms.Normalize(\n","        mean=[0.485, 0.456, 0.406],\n","        std=[0.229, 0.224, 0.225],\n","    )\n","\n","    # define transform\n","    transform = transforms.Compose([\n","        transforms.ToTensor(),\n","        normalize,\n","    ])\n","\n","    dataset = datasets.CIFAR10(\n","        root=data_dir, train=False,\n","        download=True, transform=transform,\n","    )\n","\n","    data_loader = torch.utils.data.DataLoader(\n","        dataset, batch_size=batch_size, shuffle=shuffle,\n","        num_workers=num_workers, pin_memory=pin_memory,\n","    )\n","    loader = {\"Test\":data_loader}\n","    dataset_sizes = {\"Test\": len(dataset)}\n","    return loader, dataset_sizes"],"execution_count":5,"outputs":[]},{"cell_type":"code","metadata":{"id":"dTNTJicdGUlN","executionInfo":{"status":"ok","timestamp":1602326509382,"user_tz":-120,"elapsed":1000,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["# Training the model\n","def train_model(model, dataloaders, dataset_sizes, criterion, optimizer, tb_logger, num_epochs, scheduler=None):\n","    since = time.time()\n","\n","    best_model_wts = copy.deepcopy(model.state_dict())\n","    best_acc = 0.0\n","\n","    for epoch in range(num_epochs):\n","        print('Epoch {}/{}'.format(epoch+1, num_epochs))\n","        print('-' * 10)\n","\n","        # Each epoch has a training and validation phase\n","        for phase in ['Train', 'Valid']:\n","            if phase == 'Train':\n","                if scheduler:\n","                    scheduler.step()\n","                model.train()  # Set model to training mode\n","            else:\n","                model.eval()   # Set model to evaluate mode\n","\n","            running_loss = 0.0\n","            running_corrects = 0\n","\n","            # Iterate over data.\n","            for inputs, labels in dataloaders[phase]:\n","                inputs = inputs.to(DEVICE)\n","                labels = labels.to(DEVICE)\n","                # DEVICE --> where the computation is happening\n","                # Torch.dtypes --> cuda tensors, cpu tensors\n","\n","                # zero the parameter gradients\n","                optimizer.zero_grad()\n","\n","                # forward\n","                # track history if only in train\n","                with torch.set_grad_enabled(phase == 'Train'):\n","                    outputs = model(inputs)\n","                    _, preds = torch.max(outputs, 1)\n","                    loss = criterion(outputs, labels)\n","\n","                    # backward + optimize only if in training phase\n","                    if phase == 'Train':\n","                        loss.backward()\n","                        optimizer.step()\n","\n","                # statistics\n","                running_loss += loss.item() * inputs.size(0)\n","                running_corrects += torch.sum(preds == labels.data)\n","\n","            epoch_loss = running_loss / dataset_sizes[phase]\n","            epoch_acc = running_corrects.double() / dataset_sizes[phase]\n","\n","            #Log with Tensorboard\n","            if phase=='Train':\n","                tb_logger.add_scalar('train_Loss',float(epoch_loss), epoch+1)\n","                tb_logger.add_scalar('train_Accuracy', float(epoch_acc), epoch+1)\n","            elif phase=='Valid':\n","                tb_logger.add_scalar('valid_Loss',float(epoch_loss), epoch+1)\n","                tb_logger.add_scalar('valid_Accuracy', float(epoch_acc), epoch+1)\n","\n","            print('{} Loss: {:.4f} Acc: {:.4f}'.format(\n","                phase, epoch_loss, epoch_acc))\n","\n","            # deep copy the model\n","            if phase == 'Valid' and epoch_acc > best_acc:\n","                best_acc = epoch_acc\n","                best_model_wts = copy.deepcopy(model.state_dict())\n","\n","    time_elapsed = time.time() - since\n","    print('Training complete in {:.0f}m {:.0f}s'.format(\n","        time_elapsed // 60, time_elapsed % 60))\n","    print('Best val Acc: {:4f}'.format(best_acc))\n","\n","    # load best model weights\n","    model.load_state_dict(best_model_wts)\n","    return best_model, epoch_loss, best_acc\n","\n","def test_model(model, dataloaders, dataset_sizes, criterion):\n","\n","    since = time.time()\n","    \n","    with torch.no_grad():\n","        for phase in ['Test']:\n","            model.eval()   # Set model to evaluate mode\n","\n","            running_loss = 0.0\n","            running_corrects = 0\n","\n","            # Iterate over data.\n","            for inputs, labels in dataloaders[phase]:\n","                inputs = inputs.to(DEVICE)\n","                labels = labels.to(DEVICE)\n","\n","                outputs = model(inputs)\n","                _, preds = torch.max(outputs, 1)\n","                loss = criterion(outputs, labels)\n","\n","                # statistics\n","                running_loss += loss.item() * inputs.size(0)\n","                running_corrects += torch.sum(preds == labels.data)\n","\n","            epoch_loss = running_loss / dataset_sizes[phase]\n","            epoch_acc = running_corrects.double() / dataset_sizes[phase]\n","    time_elapsed = time.time() - since\n","    print('Training complete in {:.0f}m {:.0f}s'.format(\n","        time_elapsed // 60, time_elapsed % 60))\n","    print('Test Acc: {:4f}'.format(epoch_acc))\n","\n","    return epoch_acc"],"execution_count":6,"outputs":[]},{"cell_type":"code","metadata":{"id":"2u8ts9tdGVww","executionInfo":{"status":"ok","timestamp":1602331992822,"user_tz":-120,"elapsed":1000,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["class Net(nn.Module):\n","    def __init__(self, c1=32, c2=64, c3=64, l1=64):\n","        super(Net, self).__init__()\n","\n","        self.conv_block = nn.Sequential(OrderedDict([\n","          ('conv1', nn.Conv2d(3, c1, 3)),\n","          ('relu1', nn.ReLU()),\n","          ('pool1', nn.MaxPool2d(2,2)),\n","          ('conv2', nn.Conv2d(c1,c2,3)),\n","          ('relu2', nn.ReLU()),\n","          ('pool2', nn.MaxPool2d(2,2)),\n","          ('conv3', nn.Conv2d(c2,c2,3)),\n","          ('relu3', nn.ReLU()),\n","          ('flatten', nn.Flatten())\n","        ]))\n","        self.fc_block = nn.Sequential(OrderedDict([\n","          ('fc1', nn.Linear(1024, l1)),\n","          ('relu1', nn.ReLU()),\n","          ('fc2', nn.Linear(l1, 10))\n","        ]))\n","\n","    def forward(self, x):\n","        x = self.conv_block(x)\n","        x = self.fc_block(x)\n","        return x"],"execution_count":28,"outputs":[]},{"cell_type":"code","metadata":{"id":"eIG-RlrYO0ZK"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Dh5-52CQO0Qz"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"Php9nMkAGXrf","executionInfo":{"status":"ok","timestamp":1602326522062,"user_tz":-120,"elapsed":12498,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}},"outputId":"d9c209de-1483-48d0-d920-3ea2847bc0cf","colab":{"base_uri":"https://localhost:8080/","height":117,"referenced_widgets":["2c218057107d41698a168d956a9abdf6","9c97b6aa0b394200ab1abb40bd6d12b2","6e86a67843b14ce684e1fd522909009e","21167fab426d4a71a93ac2c3bad04d27","e589c074f203450db3c7c1211cad5584","569ee684990547309e666dd42808337f","a99d36384a224757a8b7297c4423ccef","0c10225f3e8a46caa5d963d9bbf9348d"]}},"source":["SEED=42\n","DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n","\n","data_dir=\"./data\"\n","batch_size=64\n","augment=False\n","\n","valid_size=0.2\n","shuffle=True\n","\n","learning_rate = 0.001\n","\n","trainloaders, train_dataset_sizes = get_train_valid_loader(data_dir=data_dir, batch_size=batch_size,\n","                       augment=augment, random_seed=SEED, valid_size=valid_size,\n","                       shuffle=shuffle, show_sample=False, num_workers=1, pin_memory=True)\n","testloader, test_dataset_sizes = get_test_loader(data_dir=data_dir, batch_size=64, shuffle=False,\n","                             num_workers=1, pin_memory=True)\n"],"execution_count":8,"outputs":[{"output_type":"stream","text":["Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz\n"],"name":"stdout"},{"output_type":"display_data","data":{"application/vnd.jupyter.widget-view+json":{"model_id":"2c218057107d41698a168d956a9abdf6","version_minor":0,"version_major":2},"text/plain":["HBox(children=(FloatProgress(value=1.0, bar_style='info', max=1.0), HTML(value='')))"]},"metadata":{"tags":[]}},{"output_type":"stream","text":["Extracting ./data/cifar-10-python.tar.gz to ./data\n","Files already downloaded and verified\n","Files already downloaded and verified\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"2zc2G7viHNbb","executionInfo":{"status":"ok","timestamp":1602326684404,"user_tz":-120,"elapsed":929,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["LOG_DIR = 'runs'\n","os.makedirs(LOG_DIR, exist_ok=True)"],"execution_count":10,"outputs":[]},{"cell_type":"code","metadata":{"id":"oNRVtxwEO8r2"},"source":["model = Net().to(DEVICE)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"-RSwFLSlO1fs"},"source":["if DEVICE == \"cuda\":\n","    if torch.cuda.device_count() > 1:\n","        model = nn.DataParallel(model)\n","model = model.to(DEVICE)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"VUJXc765Q4V2"},"source":[""],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"rEpzJ9ACQ4Ok","executionInfo":{"status":"ok","timestamp":1602330336045,"user_tz":-120,"elapsed":945,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["def train(config, checkpoint_dir = None, data_dir=\"./data\"):\n","\n","    net = Net(config[\"c1\"], config[\"c2\"], config[\"c3\"], config[\"l1\"])\n","\n","    device = \"cpu\"\n","    if torch.cuda.is_available():\n","        device = \"cuda:0\"\n","        if torch.cuda.device_count() > 1:\n","            net = nn.DataParallel(net)\n","    net.to(device)\n","\n","    criterion = nn.CrossEntropyLoss()\n","    scheduler = None\n","    if config[\"optim\"] == \"SGD\":\n","        optimizer = optim.SGD(net.parameters(), lr=config[\"lr\"], momentum=0.9)\n","    elif config[\"optim\"] == \"Adam\":\n","        optimizer = optim.Adam(model.parameters(), lr=config[\"lr\"])\n","\n","    # The `checkpoint_dir` parameter gets passed by Ray Tune when a checkpoint\n","    # should be restored.\n","    if checkpoint_dir:\n","        checkpoint = os.path.join(checkpoint_dir, \"checkpoint\")\n","        model_state, optimizer_state = torch.load(checkpoint)\n","        net.load_state_dict(model_state)\n","        optimizer.load_state_dict(optimizer_state)\n","\n","    augment=False\n","    valid_size=0.2\n","    shuffle=True\n","    trainloaders, train_dataset_sizes = get_train_valid_loader(data_dir=data_dir, batch_size=config[\"batchsize\"],\n","                       augment=augment, random_seed=SEED, valid_size=valid_size,\n","                       shuffle=shuffle, show_sample=False, num_workers=8, pin_memory=True)\n","    testloader, test_dataset_sizes = get_test_loader(data_dir=data_dir, batch_size=64, shuffle=False,\n","                             num_workers=8, pin_memory=True)\n","    \n","    tb_logger = SummaryWriter(os.path.join(LOG_DIR,\"test_exp2\"))\n","    num_epochs = 10\n","\n","    model, val_loss, val_acc = train_model(net, trainloaders, train_dataset_sizes, criterion, optimizer, tb_logger, num_epochs)\n","    \n","    test_acc = test_model(net, testloader, test_dataset_sizes, criterion)\n","\n","    tune.report(loss=val_loss, accuracy=val_acc)\n","    tb_logger.close()\n","\n","\n","    \n","\n","\n"],"execution_count":21,"outputs":[]},{"cell_type":"code","metadata":{"id":"bJLrT9DnO1oJ","executionInfo":{"status":"ok","timestamp":1602331966376,"user_tz":-120,"elapsed":963,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":["def main(num_samples=10, max_num_epochs=10, gpus_per_trial=0):\n","    data_dir = os.path.abspath(\"./data\")\n","    # load_data(data_dir)  # Download data for all trials before starting the run\n","    config = {\n","        \"c1\": tune.choice([16, 32, 64]),\n","        \"c2\": tune.choice([32, 64, 128]),\n","        \"c3\": tune.choice([64, 128, 256]),        \n","        \"l1\": tune.sample_from(lambda _: 2 ** np.random.randint(2, 9)),\n","        \"lr\": tune.loguniform(1e-4, 1e-1),\n","        \"batch_size\": tune.choice([2, 4, 8, 16])\n","    }\n","    scheduler = ASHAScheduler(\n","        metric=\"loss\",\n","        mode=\"min\",\n","        max_t=max_num_epochs,\n","        grace_period=1,\n","        reduction_factor=2)\n","    reporter = CLIReporter(\n","        # parameter_columns=[\"l1\", \"l2\", \"lr\", \"batch_size\"],\n","        metric_columns=[\"loss\", \"accuracy\", \"training_iteration\"])\n","    result = tune.run(\n","        partial(train, data_dir=data_dir),\n","        resources_per_trial={\"cpu\": 2, \"gpu\": gpus_per_trial},\n","        config=config,\n","        num_samples=num_samples,\n","        scheduler=scheduler,\n","        progress_reporter=reporter)\n","\n","    best_trial = result.get_best_trial(\"loss\", \"min\", \"last\")\n","    print(\"Best trial config: {}\".format(best_trial.config))\n","    print(\"Best trial final validation loss: {}\".format(\n","        best_trial.last_result[\"loss\"]))\n","    print(\"Best trial final validation accuracy: {}\".format(\n","        best_trial.last_result[\"accuracy\"]))\n","\n","    best_trained_model = Net(best_trial.config[\"l1\"], best_trial.config[\"l2\"])\n","    device = \"cpu\"\n","    if torch.cuda.is_available():\n","        device = \"cuda:0\"\n","        if gpus_per_trial > 1:\n","            best_trained_model = nn.DataParallel(best_trained_model)\n","    best_trained_model.to(device)\n","\n","    checkpoint_path = os.path.join(best_trial.checkpoint.value, \"checkpoint\")\n","\n","    model_state, optimizer_state = torch.load(checkpoint_path)\n","    best_trained_model.load_state_dict(model_state)\n","\n","    testloader, test_dataset_sizes = get_test_loader(data_dir=data_dir, batch_size=64, shuffle=False,\n","                             num_workers=8, pin_memory=True)\n","    test_acc = test_model(best_trained_model, testloader, test_dataset_sizes, criterion)\n","    print(\"Best trial test set accuracy: {}\".format(test_acc))"],"execution_count":26,"outputs":[]},{"cell_type":"code","metadata":{"id":"nsa6tQNMGY8_","executionInfo":{"status":"ok","timestamp":1602331969289,"user_tz":-120,"elapsed":1647,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}}},"source":[""],"execution_count":26,"outputs":[]},{"cell_type":"code","metadata":{"id":"tXvaWdvBGlSf","executionInfo":{"status":"error","timestamp":1602332019164,"user_tz":-120,"elapsed":22302,"user":{"displayName":"Naga Sai Pranay Modukuru","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GjhMI3XwNx4CHt6WxxUkyYKMr_Z7mXYGS1nuDV4_xU=s64","userId":"06974713623688666957"}},"outputId":"44fdf978-821e-4ee0-bf1f-5885fa949e8e","colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["main()"],"execution_count":29,"outputs":[{"output_type":"stream","text":["2020-10-10 12:13:17,426\tWARNING experiment.py:256 -- No name detected on trainable. Using DEFAULT.\n","2020-10-10 12:13:17,428\tINFO registry.py:65 -- Detected unknown callable for trainable. Converting to class.\n"],"name":"stderr"},{"output_type":"stream","text":["== Status ==\n","Memory usage on this node: 2.8/12.7 GiB\n","Using AsyncHyperBand: num_stopped=0\n","Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n","Resources requested: 2/2 CPUs, 0/1 GPUs, 0.0/7.13 GiB heap, 0.0/2.44 GiB objects (0/1.0 accelerator_type:K80)\n","Result logdir: /root/ray_results/DEFAULT\n","Number of trials: 10 (9 PENDING, 1 RUNNING)\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","| Trial name          | status   | loc   |   batch_size |   c1 |   c2 |   c3 |   l1 |          lr |\n","|---------------------+----------+-------+--------------+------+------+------+------+-------------|\n","| DEFAULT_fab5d_00000 | RUNNING  |       |            2 |   16 |  128 |  128 |   64 | 0.00398859  |\n","| DEFAULT_fab5d_00001 | PENDING  |       |            8 |   32 |   64 |  128 |  128 | 0.0133473   |\n","| DEFAULT_fab5d_00002 | PENDING  |       |            4 |   32 |  128 |   64 |    8 | 0.00536858  |\n","| DEFAULT_fab5d_00003 | PENDING  |       |            4 |   32 |  128 |   64 |   16 | 0.000439499 |\n","| DEFAULT_fab5d_00004 | PENDING  |       |            8 |   32 |  128 |  128 |  256 | 0.000833825 |\n","| DEFAULT_fab5d_00005 | PENDING  |       |           16 |   64 |   32 |  128 |  128 | 0.00267381  |\n","| DEFAULT_fab5d_00006 | PENDING  |       |            2 |   32 |  128 |  256 |    8 | 0.043687    |\n","| DEFAULT_fab5d_00007 | PENDING  |       |            8 |   16 |  128 |   64 |    8 | 0.000353735 |\n","| DEFAULT_fab5d_00008 | PENDING  |       |            4 |   32 |  128 |  128 |  256 | 0.0209075   |\n","| DEFAULT_fab5d_00009 | PENDING  |       |            8 |   16 |   64 |  128 |   64 | 0.000617206 |\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","\n","\n"],"name":"stdout"},{"output_type":"stream","text":["\u001b[2m\u001b[36m(pid=1318)\u001b[0m 2020-10-10 12:13:19,390\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1318)\u001b[0m \n","2020-10-10 12:13:19,584\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00000: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1318, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1318, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m 2020-10-10 12:13:21,543\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1338)\u001b[0m \n","2020-10-10 12:13:21,738\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00001: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1338, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1338, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m 2020-10-10 12:13:23,683\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1359)\u001b[0m \n","2020-10-10 12:13:23,878\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00002: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1359, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1359, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n"],"name":"stderr"},{"output_type":"stream","text":["== Status ==\n","Memory usage on this node: 2.9/12.7 GiB\n","Using AsyncHyperBand: num_stopped=0\n","Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n","Resources requested: 0/2 CPUs, 0/1 GPUs, 0.0/7.13 GiB heap, 0.0/2.44 GiB objects (0/1.0 accelerator_type:K80)\n","Result logdir: /root/ray_results/DEFAULT\n","Number of trials: 10 (3 ERROR, 7 PENDING)\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","| Trial name          | status   | loc   |   batch_size |   c1 |   c2 |   c3 |   l1 |          lr |\n","|---------------------+----------+-------+--------------+------+------+------+------+-------------|\n","| DEFAULT_fab5d_00000 | ERROR    |       |            2 |   16 |  128 |  128 |   64 | 0.00398859  |\n","| DEFAULT_fab5d_00001 | ERROR    |       |            8 |   32 |   64 |  128 |  128 | 0.0133473   |\n","| DEFAULT_fab5d_00002 | ERROR    |       |            4 |   32 |  128 |   64 |    8 | 0.00536858  |\n","| DEFAULT_fab5d_00003 | PENDING  |       |            4 |   32 |  128 |   64 |   16 | 0.000439499 |\n","| DEFAULT_fab5d_00004 | PENDING  |       |            8 |   32 |  128 |  128 |  256 | 0.000833825 |\n","| DEFAULT_fab5d_00005 | PENDING  |       |           16 |   64 |   32 |  128 |  128 | 0.00267381  |\n","| DEFAULT_fab5d_00006 | PENDING  |       |            2 |   32 |  128 |  256 |    8 | 0.043687    |\n","| DEFAULT_fab5d_00007 | PENDING  |       |            8 |   16 |  128 |   64 |    8 | 0.000353735 |\n","| DEFAULT_fab5d_00008 | PENDING  |       |            4 |   32 |  128 |  128 |  256 | 0.0209075   |\n","| DEFAULT_fab5d_00009 | PENDING  |       |            8 |   16 |   64 |  128 |   64 | 0.000617206 |\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","Number of errored trials: 3\n","+---------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------+\n","| Trial name          |   # failures | error file                                                                                                                        |\n","|---------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------|\n","| DEFAULT_fab5d_00000 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00000_0_batch_size=2,c1=16,c2=128,c3=128,l1=64,lr=0.0039886_2020-10-10_12-13-17/error.txt |\n","| DEFAULT_fab5d_00001 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00001_1_batch_size=8,c1=32,c2=64,c3=128,l1=128,lr=0.013347_2020-10-10_12-13-19/error.txt  |\n","| DEFAULT_fab5d_00002 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00002_2_batch_size=4,c1=32,c2=128,c3=64,l1=8,lr=0.0053686_2020-10-10_12-13-21/error.txt   |\n","+---------------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------+\n","\n"],"name":"stdout"},{"output_type":"stream","text":["\u001b[2m\u001b[36m(pid=1380)\u001b[0m 2020-10-10 12:13:25,743\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1380)\u001b[0m \n","2020-10-10 12:13:25,938\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00003: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1380, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1380, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m 2020-10-10 12:13:27,888\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1400)\u001b[0m \n","2020-10-10 12:13:28,080\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00004: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1400, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1400, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m 2020-10-10 12:13:30,064\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1421)\u001b[0m \n","2020-10-10 12:13:30,259\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00005: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1421, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1421, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n"],"name":"stderr"},{"output_type":"stream","text":["== Status ==\n","Memory usage on this node: 2.9/12.7 GiB\n","Using AsyncHyperBand: num_stopped=0\n","Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n","Resources requested: 0/2 CPUs, 0/1 GPUs, 0.0/7.13 GiB heap, 0.0/2.44 GiB objects (0/1.0 accelerator_type:K80)\n","Result logdir: /root/ray_results/DEFAULT\n","Number of trials: 10 (6 ERROR, 4 PENDING)\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","| Trial name          | status   | loc   |   batch_size |   c1 |   c2 |   c3 |   l1 |          lr |\n","|---------------------+----------+-------+--------------+------+------+------+------+-------------|\n","| DEFAULT_fab5d_00000 | ERROR    |       |            2 |   16 |  128 |  128 |   64 | 0.00398859  |\n","| DEFAULT_fab5d_00001 | ERROR    |       |            8 |   32 |   64 |  128 |  128 | 0.0133473   |\n","| DEFAULT_fab5d_00002 | ERROR    |       |            4 |   32 |  128 |   64 |    8 | 0.00536858  |\n","| DEFAULT_fab5d_00003 | ERROR    |       |            4 |   32 |  128 |   64 |   16 | 0.000439499 |\n","| DEFAULT_fab5d_00004 | ERROR    |       |            8 |   32 |  128 |  128 |  256 | 0.000833825 |\n","| DEFAULT_fab5d_00005 | ERROR    |       |           16 |   64 |   32 |  128 |  128 | 0.00267381  |\n","| DEFAULT_fab5d_00006 | PENDING  |       |            2 |   32 |  128 |  256 |    8 | 0.043687    |\n","| DEFAULT_fab5d_00007 | PENDING  |       |            8 |   16 |  128 |   64 |    8 | 0.000353735 |\n","| DEFAULT_fab5d_00008 | PENDING  |       |            4 |   32 |  128 |  128 |  256 | 0.0209075   |\n","| DEFAULT_fab5d_00009 | PENDING  |       |            8 |   16 |   64 |  128 |   64 | 0.000617206 |\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","Number of errored trials: 6\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","| Trial name          |   # failures | error file                                                                                                                          |\n","|---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------|\n","| DEFAULT_fab5d_00000 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00000_0_batch_size=2,c1=16,c2=128,c3=128,l1=64,lr=0.0039886_2020-10-10_12-13-17/error.txt   |\n","| DEFAULT_fab5d_00001 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00001_1_batch_size=8,c1=32,c2=64,c3=128,l1=128,lr=0.013347_2020-10-10_12-13-19/error.txt    |\n","| DEFAULT_fab5d_00002 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00002_2_batch_size=4,c1=32,c2=128,c3=64,l1=8,lr=0.0053686_2020-10-10_12-13-21/error.txt     |\n","| DEFAULT_fab5d_00003 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00003_3_batch_size=4,c1=32,c2=128,c3=64,l1=16,lr=0.0004395_2020-10-10_12-13-23/error.txt    |\n","| DEFAULT_fab5d_00004 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00004_4_batch_size=8,c1=32,c2=128,c3=128,l1=256,lr=0.00083382_2020-10-10_12-13-25/error.txt |\n","| DEFAULT_fab5d_00005 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00005_5_batch_size=16,c1=64,c2=32,c3=128,l1=128,lr=0.0026738_2020-10-10_12-13-28/error.txt  |\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","\n"],"name":"stdout"},{"output_type":"stream","text":["\u001b[2m\u001b[36m(pid=1442)\u001b[0m 2020-10-10 12:13:32,152\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1442)\u001b[0m \n","2020-10-10 12:13:32,347\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00006: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1442, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1442, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m 2020-10-10 12:13:34,339\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1462)\u001b[0m \n","2020-10-10 12:13:34,534\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00007: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1462, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1462, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m 2020-10-10 12:13:36,400\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1483)\u001b[0m \n","2020-10-10 12:13:36,593\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00008: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1483, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1483, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n"],"name":"stderr"},{"output_type":"stream","text":["== Status ==\n","Memory usage on this node: 2.9/12.7 GiB\n","Using AsyncHyperBand: num_stopped=0\n","Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n","Resources requested: 0/2 CPUs, 0/1 GPUs, 0.0/7.13 GiB heap, 0.0/2.44 GiB objects (0/1.0 accelerator_type:K80)\n","Result logdir: /root/ray_results/DEFAULT\n","Number of trials: 10 (9 ERROR, 1 PENDING)\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","| Trial name          | status   | loc   |   batch_size |   c1 |   c2 |   c3 |   l1 |          lr |\n","|---------------------+----------+-------+--------------+------+------+------+------+-------------|\n","| DEFAULT_fab5d_00000 | ERROR    |       |            2 |   16 |  128 |  128 |   64 | 0.00398859  |\n","| DEFAULT_fab5d_00001 | ERROR    |       |            8 |   32 |   64 |  128 |  128 | 0.0133473   |\n","| DEFAULT_fab5d_00002 | ERROR    |       |            4 |   32 |  128 |   64 |    8 | 0.00536858  |\n","| DEFAULT_fab5d_00003 | ERROR    |       |            4 |   32 |  128 |   64 |   16 | 0.000439499 |\n","| DEFAULT_fab5d_00004 | ERROR    |       |            8 |   32 |  128 |  128 |  256 | 0.000833825 |\n","| DEFAULT_fab5d_00005 | ERROR    |       |           16 |   64 |   32 |  128 |  128 | 0.00267381  |\n","| DEFAULT_fab5d_00006 | ERROR    |       |            2 |   32 |  128 |  256 |    8 | 0.043687    |\n","| DEFAULT_fab5d_00007 | ERROR    |       |            8 |   16 |  128 |   64 |    8 | 0.000353735 |\n","| DEFAULT_fab5d_00008 | ERROR    |       |            4 |   32 |  128 |  128 |  256 | 0.0209075   |\n","| DEFAULT_fab5d_00009 | PENDING  |       |            8 |   16 |   64 |  128 |   64 | 0.000617206 |\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","Number of errored trials: 9\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","| Trial name          |   # failures | error file                                                                                                                          |\n","|---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------|\n","| DEFAULT_fab5d_00000 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00000_0_batch_size=2,c1=16,c2=128,c3=128,l1=64,lr=0.0039886_2020-10-10_12-13-17/error.txt   |\n","| DEFAULT_fab5d_00001 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00001_1_batch_size=8,c1=32,c2=64,c3=128,l1=128,lr=0.013347_2020-10-10_12-13-19/error.txt    |\n","| DEFAULT_fab5d_00002 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00002_2_batch_size=4,c1=32,c2=128,c3=64,l1=8,lr=0.0053686_2020-10-10_12-13-21/error.txt     |\n","| DEFAULT_fab5d_00003 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00003_3_batch_size=4,c1=32,c2=128,c3=64,l1=16,lr=0.0004395_2020-10-10_12-13-23/error.txt    |\n","| DEFAULT_fab5d_00004 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00004_4_batch_size=8,c1=32,c2=128,c3=128,l1=256,lr=0.00083382_2020-10-10_12-13-25/error.txt |\n","| DEFAULT_fab5d_00005 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00005_5_batch_size=16,c1=64,c2=32,c3=128,l1=128,lr=0.0026738_2020-10-10_12-13-28/error.txt  |\n","| DEFAULT_fab5d_00006 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00006_6_batch_size=2,c1=32,c2=128,c3=256,l1=8,lr=0.043687_2020-10-10_12-13-30/error.txt     |\n","| DEFAULT_fab5d_00007 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00007_7_batch_size=8,c1=16,c2=128,c3=64,l1=8,lr=0.00035373_2020-10-10_12-13-32/error.txt    |\n","| DEFAULT_fab5d_00008 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00008_8_batch_size=4,c1=32,c2=128,c3=128,l1=256,lr=0.020908_2020-10-10_12-13-34/error.txt   |\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","\n"],"name":"stdout"},{"output_type":"stream","text":["\u001b[2m\u001b[36m(pid=1503)\u001b[0m 2020-10-10 12:13:38,580\tERROR function_runner.py:233 -- Runner Thread raised error.\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m Exception in thread Thread-2:\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m Traceback (most recent call last):\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/lib/python3.6/threading.py\", line 916, in _bootstrap_inner\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     self.run()\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 246, in run\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     raise e\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     self._entrypoint()\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     self._status_reporter.get_checkpoint())\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m     output = train_func(config, checkpoint_dir=checkpoint_dir)\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m   File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m KeyError: 'optim'\n","\u001b[2m\u001b[36m(pid=1503)\u001b[0m \n","2020-10-10 12:13:38,776\tERROR trial_runner.py:567 -- Trial DEFAULT_fab5d_00009: Error processing event.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py\", line 515, in _process_trial\n","    result = self.trial_executor.fetch_result(trial)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py\", line 488, in fetch_result\n","    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/worker.py\", line 1428, in get\n","    raise value.as_instanceof_cause()\n","ray.exceptions.RayTaskError(TuneError): \u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1503, ip=172.28.0.2)\n","  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task\n","  File \"python/ray/_raylet.pyx\", line 438, in ray._raylet.execute_task.function_executor\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py\", line 336, in train\n","    result = self.step()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 340, in step\n","    self._report_thread_runner_error(block=True)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 459, in _report_thread_runner_error\n","    .format(err_tb_str)))\n","ray.tune.error.TuneError: Trial raised an exception. Traceback:\n","\u001b[36mray::ImplicitFunc.train()\u001b[39m (pid=1503, ip=172.28.0.2)\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 227, in run\n","    self._entrypoint()\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 290, in entrypoint\n","    self._status_reporter.get_checkpoint())\n","  File \"/usr/local/lib/python3.6/dist-packages/ray/tune/function_runner.py\", line 499, in _trainable_func\n","    output = train_func(config, checkpoint_dir=checkpoint_dir)\n","  File \"<ipython-input-21-6d676047dfc4>\", line 14, in train\n","KeyError: 'optim'\n"],"name":"stderr"},{"output_type":"stream","text":["== Status ==\n","Memory usage on this node: 2.9/12.7 GiB\n","Using AsyncHyperBand: num_stopped=0\n","Bracket: Iter 8.000: None | Iter 4.000: None | Iter 2.000: None | Iter 1.000: None\n","Resources requested: 0/2 CPUs, 0/1 GPUs, 0.0/7.13 GiB heap, 0.0/2.44 GiB objects (0/1.0 accelerator_type:K80)\n","Result logdir: /root/ray_results/DEFAULT\n","Number of trials: 10 (10 ERROR)\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","| Trial name          | status   | loc   |   batch_size |   c1 |   c2 |   c3 |   l1 |          lr |\n","|---------------------+----------+-------+--------------+------+------+------+------+-------------|\n","| DEFAULT_fab5d_00000 | ERROR    |       |            2 |   16 |  128 |  128 |   64 | 0.00398859  |\n","| DEFAULT_fab5d_00001 | ERROR    |       |            8 |   32 |   64 |  128 |  128 | 0.0133473   |\n","| DEFAULT_fab5d_00002 | ERROR    |       |            4 |   32 |  128 |   64 |    8 | 0.00536858  |\n","| DEFAULT_fab5d_00003 | ERROR    |       |            4 |   32 |  128 |   64 |   16 | 0.000439499 |\n","| DEFAULT_fab5d_00004 | ERROR    |       |            8 |   32 |  128 |  128 |  256 | 0.000833825 |\n","| DEFAULT_fab5d_00005 | ERROR    |       |           16 |   64 |   32 |  128 |  128 | 0.00267381  |\n","| DEFAULT_fab5d_00006 | ERROR    |       |            2 |   32 |  128 |  256 |    8 | 0.043687    |\n","| DEFAULT_fab5d_00007 | ERROR    |       |            8 |   16 |  128 |   64 |    8 | 0.000353735 |\n","| DEFAULT_fab5d_00008 | ERROR    |       |            4 |   32 |  128 |  128 |  256 | 0.0209075   |\n","| DEFAULT_fab5d_00009 | ERROR    |       |            8 |   16 |   64 |  128 |   64 | 0.000617206 |\n","+---------------------+----------+-------+--------------+------+------+------+------+-------------+\n","Number of errored trials: 10\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","| Trial name          |   # failures | error file                                                                                                                          |\n","|---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------|\n","| DEFAULT_fab5d_00000 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00000_0_batch_size=2,c1=16,c2=128,c3=128,l1=64,lr=0.0039886_2020-10-10_12-13-17/error.txt   |\n","| DEFAULT_fab5d_00001 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00001_1_batch_size=8,c1=32,c2=64,c3=128,l1=128,lr=0.013347_2020-10-10_12-13-19/error.txt    |\n","| DEFAULT_fab5d_00002 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00002_2_batch_size=4,c1=32,c2=128,c3=64,l1=8,lr=0.0053686_2020-10-10_12-13-21/error.txt     |\n","| DEFAULT_fab5d_00003 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00003_3_batch_size=4,c1=32,c2=128,c3=64,l1=16,lr=0.0004395_2020-10-10_12-13-23/error.txt    |\n","| DEFAULT_fab5d_00004 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00004_4_batch_size=8,c1=32,c2=128,c3=128,l1=256,lr=0.00083382_2020-10-10_12-13-25/error.txt |\n","| DEFAULT_fab5d_00005 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00005_5_batch_size=16,c1=64,c2=32,c3=128,l1=128,lr=0.0026738_2020-10-10_12-13-28/error.txt  |\n","| DEFAULT_fab5d_00006 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00006_6_batch_size=2,c1=32,c2=128,c3=256,l1=8,lr=0.043687_2020-10-10_12-13-30/error.txt     |\n","| DEFAULT_fab5d_00007 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00007_7_batch_size=8,c1=16,c2=128,c3=64,l1=8,lr=0.00035373_2020-10-10_12-13-32/error.txt    |\n","| DEFAULT_fab5d_00008 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00008_8_batch_size=4,c1=32,c2=128,c3=128,l1=256,lr=0.020908_2020-10-10_12-13-34/error.txt   |\n","| DEFAULT_fab5d_00009 |            1 | /root/ray_results/DEFAULT/DEFAULT_fab5d_00009_9_batch_size=8,c1=16,c2=64,c3=128,l1=64,lr=0.00061721_2020-10-10_12-13-36/error.txt   |\n","+---------------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------+\n","\n"],"name":"stdout"},{"output_type":"error","ename":"TuneError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mTuneError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-29-263240bbee7e>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mmain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-26-b8e0e4c82991>\u001b[0m in \u001b[0;36mmain\u001b[0;34m(num_samples, max_num_epochs, gpus_per_trial)\u001b[0m\n\u001b[1;32m     25\u001b[0m         \u001b[0mnum_samples\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mnum_samples\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     26\u001b[0m         \u001b[0mscheduler\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mscheduler\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 27\u001b[0;31m         progress_reporter=reporter)\n\u001b[0m\u001b[1;32m     28\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     29\u001b[0m     \u001b[0mbest_trial\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_best_trial\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"loss\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"min\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"last\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.6/dist-packages/ray/tune/tune.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, loggers, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint)\u001b[0m\n\u001b[1;32m    425\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    426\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 427\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    428\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    429\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0merror\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Trials did not complete: %s\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mTuneError\u001b[0m: ('Trials did not complete', [DEFAULT_fab5d_00000, DEFAULT_fab5d_00001, DEFAULT_fab5d_00002, DEFAULT_fab5d_00003, DEFAULT_fab5d_00004, DEFAULT_fab5d_00005, DEFAULT_fab5d_00006, DEFAULT_fab5d_00007, DEFAULT_fab5d_00008, DEFAULT_fab5d_00009])"]}]},{"cell_type":"code","metadata":{"id":"WVqO33LaU4sp"},"source":[""],"execution_count":null,"outputs":[]}]}